name: workflow1

on: [push]

permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  job:
    runs-on: ubuntu-latest
    services:
      dex:
        image: ghcr.io/seankhliao/dex-config
        ports:
          - 80:8080
    steps:
      # Actions have access to two special environment variables ACTIONS_CACHE_URL and ACTIONS_RUNTIME_TOKEN. Inline step scripts in workflows do not see these variables. 
      - uses: actions/github-script@v6
        id: script
        timeout-minutes: 10
        with:
          debug: true
          script: |
            const token = process.env['ACTIONS_RUNTIME_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
            core.setOutput('IDTOKENURL', runtimeUrl.trim())
      - run: |
          GH_TOKEN_RES=$(curl -H "Authorization: bearer  ${{steps.script.outputs.TOKEN}}" ${{steps.script.outputs.IDTOKENURL}}  -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}")
          # output: {"count":1844,"value":"***"}

          GH_ID_TOKEN=$(jq -r .value <<< $GH_TOKEN_RES)

          curl -v http://127.0.0.1/.well-known/openid-configuration

          curl -v http://127.0.0.1/token -d "subject_token=$GH_ID_TOKEN&subject_token_type=urn:ietf:params:oauth:token-type:id_token&audience=circleci&grant_type=urn:ietf:params:oauth:grant-type:token-exchange&requested_token_type=urn:ietf:params:oauth:token-type:id_token&scope=groups openid federated:id"
        id: idtoken
